# Generated by Django 5.0 on 2025-11-18 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes (1-1440)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='energy_level',
            field=models.IntegerField(choices=[(1, 'Very Draining'), (2, 'Somewhat Draining'), (3, 'Somewhat Energizing'), (4, 'Very Energizing')]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
