# Generated by Django 5.0 on 2025-11-18 03:46

from django.db import migrations


def migrate_energy_levels(apps, schema_editor):
    """
    Transform energy_level values from old scale to new scale.
    Old scale: -2, -1, 0, 1, 2
    New scale: 1, 2, 3, 4
    Mapping: old_value + 3 = new_value (with 0 mapped to 2)
    """
    Activity = apps.get_model('energy_tracker', 'Activity')

    # Mapping dictionary
    energy_mapping = {
        -2: 1,  # Very Draining
        -1: 2,  # Somewhat Draining
        0: 2,   # Neutral -> Somewhat Draining (conservative)
        1: 3,   # Somewhat Energizing
        2: 4,   # Very Energizing
    }

    for activity in Activity.objects.all():
        if activity.energy_level in energy_mapping:
            activity.energy_level = energy_mapping[activity.energy_level]
            activity.save(update_fields=['energy_level'])


def reverse_migrate_energy_levels(apps, schema_editor):
    """
    Reverse transformation for rollback.
    New scale: 1, 2, 3, 4
    Old scale: -2, -1, 0, 1, 2
    """
    Activity = apps.get_model('energy_tracker', 'Activity')

    # Reverse mapping
    reverse_mapping = {
        1: -2,  # Very Draining
        2: -1,  # Somewhat Draining (we map back to -1, not 0)
        3: 1,   # Somewhat Energizing
        4: 2,   # Very Energizing
    }

    for activity in Activity.objects.all():
        if activity.energy_level in reverse_mapping:
            activity.energy_level = reverse_mapping[activity.energy_level]
            activity.save(update_fields=['energy_level'])


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0002_activity_duration_alter_activity_energy_level_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_energy_levels, reverse_migrate_energy_levels),
    ]
