# Generated by Django 5.0 on 2025-11-18 04:09

from django.db import migrations, models


def transform_energy_levels_forward(apps, schema_editor):
    """Transform energy levels from old scale (1,2,3,4) to new scale (-2,-1,1,2)"""
    Activity = apps.get_model('energy_tracker', 'Activity')

    # Mapping: 1→-2, 2→-1, 3→1, 4→2
    mapping = {1: -2, 2: -1, 3: 1, 4: 2}

    for activity in Activity.objects.all():
        if activity.energy_level in mapping:
            activity.energy_level = mapping[activity.energy_level]
            activity.save()


def transform_energy_levels_reverse(apps, schema_editor):
    """Reverse transformation from new scale (-2,-1,1,2) back to old scale (1,2,3,4)"""
    Activity = apps.get_model('energy_tracker', 'Activity')

    # Reverse mapping: -2→1, -1→2, 1→3, 2→4
    reverse_mapping = {-2: 1, -1: 2, 1: 3, 2: 4}

    for activity in Activity.objects.all():
        if activity.energy_level in reverse_mapping:
            activity.energy_level = reverse_mapping[activity.energy_level]
            activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0003_migrate_energy_level_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='energy_level',
            field=models.IntegerField(choices=[(-2, 'Very Draining'), (-1, 'Somewhat Draining'), (1, 'Somewhat Energizing'), (2, 'Very Energizing')]),
        ),
        migrations.RunPython(
            transform_energy_levels_forward,
            reverse_code=transform_energy_levels_reverse
        ),
    ]
