# Generated by Django 5.0 on 2025-11-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0002_userprofile'),
        ('energy_tracker', '0004_change_energy_scale'),
    ]

    operations = [
    ]
