# Generated by Django 5.0 on 2025-11-29 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0005_merge_0002_userprofile_0004_change_energy_scale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-activity_date'], name='energy_trac_user_id_6da0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'activity_date'], name='energy_trac_user_id_cce05c_idx'),
        ),
    ]
