# Generated by Django 5.1.3 on 2025-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy_tracker", "0006_activity_energy_trac_user_id_6da0e9_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("variant_shown", "Variant Shown"),
                            ("button_click", "Button Click"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        choices=[("kudos", "Kudos"), ("thanks", "Thanks")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Browser session identifier", max_length=100
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "variant"],
                        name="energy_trac_event_t_e254dd_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="energy_trac_session_e1ad3f_idx"
                    ),
                    models.Index(
                        fields=["-timestamp"], name="energy_trac_timesta_24b4b1_idx"
                    ),
                ],
            },
        ),
    ]
