# Generated by Django 5.1.3 on 2025-12-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("energy_tracker", "0007_abtestevent"),
    ]

    operations = []
